POST http://localhost:3000/auth/login
content-type: application/json

{
    "Email": "1@gmail.com",
    "Password": "123456"
}

###

GET http://localhost:3000/auth/me
authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJFbWFpbCI6IjFAZ21haWwuY29tIiwiaWF0IjoxNzM5ODExNDA3LCJleHAiOjE3Mzk4OTc4MDd9.7tuFcJCASgE5xT_CrlEQjmOh9ombHhRBDTfCgCdcMcY