POST http://localhost:3000/auth/login
content-type: application/json

{
    "username": "test",
    "password": "123456"
}

###

GET http://localhost:3000/auth/me
authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InRlc3QiLCJpYXQiOjE3Mzk0NzQyNzgsImV4cCI6MTczOTU2MDY3OH0.R3mL3E4oIEZi6L8ppdU4hAAEr-8WlD0P5LrgGB7fxvA